solana_subreddit_dbt:
  outputs:
    dev:
      dataset: solana_subreddit_posts
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /path/to/keyfile
      location: US
      method: service-account
      priority: interactive
      project: solana-subreddit-scraper
      threads: 4
      type: bigquery
  target: dev
